### ISSUE TITLE
Its posible a one script for all devices?

### ISSUE THREAD

**Issue by DAVIZINH0** [w1tw0lf/Unifi-Device-info#9]
Hello!.

I have a lot of devices in my setup:
- 1 gateway ultra
- 1 poe switch ultra 16
- 1 switch flex mini
- 1 switch flex mini 2.5
- 4 aps U7 PRO

and i see a lot of erros because is to many connection to the controller. 

I have a idea, it is posible to create a one script for all? one script when the user puts the macs of the switches, and macs of the aps. and obtain the information in one connection.

its only a idea :-)

**Comment by w1tw0lf** [comment]
I have made a script that does this perfectly, but not sure how to grab the json files into home assistant to create the sensors

https://github.com/w1tw0lf/Unifi-Device-info/blob/main/unifi%20share.py

**Comment by DAVIZINH0** [comment]
first try, error login :-(

`sudo python3 unifi_unificado.py
Traceback (most recent call last):
  File "unifi_unificado.py", line 19, in <module>
    client = Controller(host, username, password, port, version, site_id=site_id, ssl_verify=verify_ssl)
  File "/usr/lib/python3.8/site-packages/pyunifi/controller.py", line 113, in __init__
    self._login()
  File "/usr/lib/python3.8/site-packages/pyunifi/controller.py", line 195, in _login
    raise APIError(
pyunifi.controller.APIError: Login failed - status code: 429`

**Comment by w1tw0lf** [comment]
The status code 429 means that you hitting the rate limit. Disable the scirpts from running in HA while testing.

**Comment by DAVIZINH0** [comment]
> The status code 429 means that you hitting the rate limit. Disable the scirpts from running in HA while testing.

jeje, perfect!! thanks

**Comment by DAVIZINH0** [comment]
ok.
Now it works.

I will search information about to import this in home assistant. Maybe publish in mqtt will be a good idea.
I think on it and tell you.

About the script i found 2 posible improves:
- my gateway ultra not apears as device. the model is "Model": "UDRULT"
- my switch have temperature information and its not include: "Model": "USPM16P"
- in the device.json apears 2 times the "Model": "USPM16P"

**Comment by w1tw0lf** [comment]
Perfect. If you can expand/add from your side, will be perfect.

Like the idea of going for mqtt. Let's see if we can make it happen.

**Comment by DAVIZINH0** [comment]
ok,  my know of python is very very bad :-(
But I try to help

one change. in line 51 if you change
    if type == 'usw':

for this:
    if type == 'usw' or type == 'udm':

now the gateway ultra its include in the report.


I keep testing, but i dont know why duplicate one device ( "Model": "USPM16P", "Type": "usw")
this device apears to times in the device.json

**Comment by w1tw0lf** [comment]
Mine just as bad......

Have a look here, https://ubntwiki.com/products/software/unifi-controller/api

It is a document on the API. Have some time tomorrow, will see if I can redo the script.

**Comment by w1tw0lf** [comment]
> 
> one change. in line 51 if you change if type == 'usw':
> 
> for this: if type == 'usw' or type == 'udm':
> 
 
This is way you getting dupplicate mostlikely.... I would say you need to split and not do "or".... 

if type == 'usw':
..............
elif type == 'udm':
......


I don't have a dream machine in order to pull info and see what stats would be nice to have in home assistant.

**Comment by DAVIZINH0** [comment]
The duplicate apears before i made the change.
But I will try

**Comment by DAVIZINH0** [comment]
I have a idea, maybe stupid idea but simple.
my knowledge is limited and this idea es very very simple.

One script that output a file for each device.
the file have the comand to make a print of the jsondump. with the information

after this, in home assistant cant create a sensor like now that lauch this file (8 devices, 8 sensors, and obtain the data of this files)

with this method this was the procedure:
- only one connection to the unifi to obtain 8 files
- 8 sensors type command that launch the 8 files.
- each file make print of data for each device (in each file)
- the sensor obtain the data and other sensors take the info of the principal sensor.


This is a maybe long way, and maybe stupid idea. jeje
But im try to learn how to publish the information for mqtt and i dont have the enought knoledge to this :-(

**Comment by w1tw0lf** [comment]
I have already created the script that does that, will need to adjust to create mqtt data.

I am on holiday till next year. Will play around with it when back home again.

**Comment by DAVIZINH0** [comment]
> I have already created the script that does that, will need to adjust to create mqtt data.
> 
> I am on holiday till next year. Will play around with it when back home again.

WOW!!! great!!

enjoy your holidays man!!!

**Comment by DAVIZINH0** [comment]
Hello
Im now in a travel ouf of home.
I test it in a few days

**Comment by DAVIZINH0** [comment]
Hello again. 
Im here again.
I launch it in a terminal an works with my cloud gateway ultra. report to mqtt the 11 devices!!!
Great work!!!

Now its time to pass this information to home assistant.
I read about this and exist 2 methods:
1.- the python needs to use the autodiscover of home assistant. I dont know how to make this posible.
2.- create custom devices and sensors in the configuration.yaml (this will be easy i think)

This week I will try to explore the second option, the first is hard to me :-(

After this, the next step is that home assistant launch this script each xx seconds. i think this will be easy too.

**Comment by DAVIZINH0** [comment]
Hello again.

I am thinking on it today. I think the most eficient implementation is autodiscovery of home assistant.
With this method, the python scrip publish the information directly to home assistant and apears the device and the entities asociated for this device.

I dont have knowledge in python, im a totaly noob with python, jejeje
But im looking for information and use copilot to try to find any solution for this problem.

Copilot say to me that we can use the paho library tu publish a device and entities to mqtt and home assistant detect it with the autodiscovery.

copilot say to me this example:
`import paho.mqtt.client as mqtt
import json

# MQTT broker configuration
MQTT_BROKER = "your_mqtt_broker"
MQTT_PORT = 1883
MQTT_USER = "your_username"
MQTT_PASSWORD = "your_password"

# Device information
DEVICE_NAME = "my_device"
DEVICE_ID = "my_device_id"
DEVICE_MANUFACTURER = "my_manufacturer"
DEVICE_MODEL = "my_model"

# Entity information
ENTITIES = [
    {
        "name": "Temperature",
        "unique_id": "temperature_1",
        "device_class": "temperature",
        "unit_of_measurement": "°C",
        "state_topic": f"homeassistant/sensor/{DEVICE_ID}/temperature/state"
    },
    {
        "name": "Humidity",
        "unique_id": "humidity_1",
        "device_class": "humidity",
        "unit_of_measurement": "%",
        "state_topic": f"homeassistant/sensor/{DEVICE_ID}/humidity/state"
    }
]

# Function to publish entity discovery information
def publish_discovery_info(client):
    for entity in ENTITIES:
        config_topic = f"homeassistant/sensor/{DEVICE_ID}/{entity['unique_id']}/config"
        config_payload = {
            "name": entity["name"],
            "unique_id": entity["unique_id"],
            "device_class": entity["device_class"],
            "unit_of_measurement": entity["unit_of_measurement"],
            "state_topic": entity["state_topic"],
            "device": {
                "identifiers": [DEVICE_ID],
                "name": DEVICE_NAME,
                "manufacturer": DEVICE_MANUFACTURER,
                "model": DEVICE_MODEL
            }
        }
        client.publish(config_topic, json.dumps(config_payload), retain=True)

# Connect to the MQTT broker
client = mqtt.Client()
client.username_pw_set(MQTT_USER, MQTT_PASSWORD)
client.connect(MQTT_BROKER, MQTT_PORT, 60)

# Publish entity discovery information
publish_discovery_info(client)

# Keep the connection open
client.loop_forever()
`

and copilot say this aditional information:
This script sets up a device with two entities (temperature and humidity) and publishes the configuration to the MQTT broker so that Home Assistant can automatically discover them.

Make sure to replace "your_mqtt_broker", "your_username", "your_password", "my_device", "my_device_id", "my_manufacturer", and "my_model" with the appropriate information for your setup.


is this information usefull?
i don know how to implement. but i think is very similar to your aproach. but the publish to mqtt its diferent because with this aproach the publis topic is diferent. isn`t it???

**Comment by w1tw0lf** [comment]
Seems like an great idea, will have to dig into it as well and see what I can come up with.

**Comment by w1tw0lf** [comment]
1st go and it seems to work correctly.....

https://github.com/w1tw0lf/Unifi-Device-info/blob/main/unifi%20share%20mqtt.py

If the script runs on home assistant, we will need to figure out what needs to be used instead of paho.mqtt. It is not on home assistant.

**Comment by w1tw0lf** [comment]
Finally fixed and working correctly.

Here is what I did:

Added https://github.com/AlexxIT/PythonScriptsPro?tab=readme-ov-file via HACS
In configuration.yaml added
```
python_script:
  requirements:
  - pyunifi
 ```
Then created automation:
```
alias: Unifi
description: ""
triggers:
  - trigger: time_pattern
    seconds: "30"
conditions: []
actions:
  - action: python_script.exec
    data:
      file: python_scripts/unifi.py
mode: single
```
Thanks for the push to get this done.

**Comment by DAVIZINH0** [comment]
Wow!!!!
Great push this night!!!

I will test it today

Thanks for your work!!!!!

**Comment by w1tw0lf** [comment]
Pleasure.

There is only one issue, not big one, the way it creates the sensor name for a device. It will duplicate the name. If a name of a device is closet ap, it will creater a sensor, sensor.closet_ap_closet_ap.

**Comment by DAVIZINH0** [comment]
yeah!!! WORKING FINE.
one sensor with all the parameters as atributes.

It runs every 30seconds and works perfect!!


I have another idea but i dont know if its easy or dificult.
Create each parameter as a sensor in the same device.
For the people it will be very interesting if each information is a single sensor, per device.

This will be great and you can share it in community of home assistant, a lot of people will be very happy!!!

**Comment by w1tw0lf** [comment]
Have you tried the 6ghz network lines, does it work ? I don't have an ap7 to test with.

Personally, I think it is perfect the way it is, as you can add the attributes just as easy to any card as a normal sensor. I recreated the cards as shown and works perfectly. 

As an example
```
{{ state_attr('sensor.*switch*', 'active_ports')['port1'] }}
```

**Comment by DAVIZINH0** [comment]
Well, are diferents points of view. this was only a idea :-)

About the 6ghz wifi. yes it works fine. I modify the script and report correctly the device connected to the 6ghz band. you can see here

![Image](https://github.com/user-attachments/assets/466a1b45-3d16-48e7-89bf-ce040d0340f3)

i need no monitoring the activity because in my 4 aps, apears as 0 and this is strange

**Comment by w1tw0lf** [comment]
Will look into it, but it would mean rewriting the entire code. It has been a huge learning curve to get it to where it is now.

Perfect. Will add on the 6ghz.

Want to spend some time in cleaning up a bit, like -1 on the score means there is no device connected on that frequency. Also want it to report only what is there.

**Comment by DAVIZINH0** [comment]
dont worry, your work with this was incredible and very usefull!!

thanks a lot again!!!

**Comment by w1tw0lf** [comment]
Closing this one as the goal has been achieved. There is a new update on the script with more attributes and added the 6ghz as well.

**Comment by DAVIZINH0** [comment]
hello @w1tw0lf 
im seeing that you are implementing some things in the scripts to the radio wifi 2.4ghz and 5ghz.
do you need help to implement the same things in the 6ghz band?
i can help you testing or obtaining information if you want. (i have the u7pro with 6ghz band, and i have setup a one wifi sid with 6ghz band)

**Comment by w1tw0lf** [comment]
Hi @DAVIZINH0 

Only thing that is missing for the 6ghz is the per ssid info as was done for 2.4 and 5ghz.

Will have a go at it and see if I can add it for testing.

**Comment by DAVIZINH0** [comment]
> Hi [@DAVIZINH0](https://github.com/DAVIZINH0)
> 
> Only thing that is missing for the 6ghz is the per ssid info as was done for 2.4 and 5ghz.
> 
> Will have a go at it and see if I can add it for testing.

ok, if you need help. tell me :-)

**Comment by w1tw0lf** [comment]
@ingoldsby can you perhaps assist with the 6ghz for ssid ? Looked at the code you added, not 100% sure how to do it.

**Comment by ingoldsby** [comment]
> > Hi [@DAVIZINH0](https://github.com/DAVIZINH0)
> > Only thing that is missing for the 6ghz is the per ssid info as was done for 2.4 and 5ghz.
> > Will have a go at it and see if I can add it for testing.
> 
> ok, if you need help. tell me :-)

Are you able to share an extract of the 'vap_table' section from your output? Sanitise the data such as "essid", "ap_mac".

The original method for differentiating 2.4Ghz and 5Ghz was based on the channels, but reading through information about the 6Ghz band, I think that won't work properly.

**Comment by w1tw0lf** [comment]
@DAVIZINH0 to get the table, login controler with ip of controller. Then change url to: https://"ip"/proxy/network/api/s/default/stat/device/"mac"
Replace "ip" with ip of controller and "mac" with the mac address of the AP that has 6gz

**Comment by DAVIZINH0** [comment]
hello.
ok i sanitise some data, i think not to much.
see it and if you need something more, tell me!

[vap_table.txt](https://github.com/user-attachments/files/18605638/vap_table.txt)

**Comment by ingoldsby** [comment]
Thanks.

That did confirm that we can't use channel ranges.

I do wonder if the following might work though:
2.4Ghz: "radio" = "ng"
5Ghz: "radio" = "na"
6Ghz: "radio" = "6e"

That holds true on my devices.

@w1tw0lf @DAVIZINH0 thoughts?

I was thinking that I could add a boolean that can be changed by the user to indicate if they want to use the 'experimental' version to split up the radio ssid's and use this process.

**Comment by w1tw0lf** [comment]
Had a quick look and seems spot on what you with your suggestion. If it works on your side, add it and let see.

Before adding booleans... I would love to change this to a proper integration via hacs, I have tried but no luck. If we can get that part done, then we can start giving user the options of what they need/want.

**Comment by DAVIZINH0** [comment]
HACS its agreat idea.
like a integration, and after maybe as a card? a card where you only need to select de main entity and paint all the card.
wow, this will be incredible. jejeje

**Comment by ingoldsby** [comment]
#16

**Comment by w1tw0lf** [comment]
@DAVIZINH0 Please download latest https://github.com/w1tw0lf/Unifi-Device-info/blob/main/unifi_mqtt.py and test

**Comment by DAVIZINH0** [comment]
> [@DAVIZINH0](https://github.com/DAVIZINH0) Please download latest https://github.com/w1tw0lf/Unifi-Device-info/blob/main/unifi_mqtt.py and test

testing now and works fine

![Image](https://github.com/user-attachments/assets/fe930ebb-a717-4ce6-9323-4902763f9d3e)

**Comment by w1tw0lf** [comment]
Mind sharing this table, radio_table_stats ? Want to look if it isn't display diffirently on your side.

**Comment by DAVIZINH0** [comment]
> radio_table_stats

ok, i attach the file

[radio_table_stats.txt](https://github.com/user-attachments/files/18616454/radio_table_stats.txt)

**Comment by w1tw0lf** [comment]
That is strange.... 
```
 "satisfaction": -1,
```
Showing it for all 3 freqeuncies. Not sure if it was asked before. it does show on the web interface ?

**Comment by DAVIZINH0** [comment]
in previous version of the unifi networks, apears the satisfaction per radio. but now not apears. only this:

![Image](https://github.com/user-attachments/assets/07972d7d-d8b3-45cb-a9ff-f87859eecae1)

**Comment by w1tw0lf** [comment]
@DAVIZINH0 if you feel like being a tester.... we just release the integration for hacs. Please test and give feed back.

**Comment by DAVIZINH0** [comment]
> [@DAVIZINH0](https://github.com/DAVIZINH0) if you feel like being a tester.... we just release the integration for hacs. Please test and give feed back.

I removed the old integration (with automation and script). and added hacs repository and hacs integration.
Works fine!!!
all my device apears to report information (cloud gateway,15poe switch, u7-pros ap, flex mini switch and flex 2.5 switches)

**Comment by DAVIZINH0** [comment]
> Perfect. Thanks for the feedback.

maybe one interesting think is the posibility to change the pool rate (refresh of the script) in the config procedure.
60seconds default its ok, but i want 30, and maybe other users want other time.
A option in the setup parameters maybe enought. 
what do you think?

**Comment by w1tw0lf** [comment]
@ingoldsby can you add the option for pole interval?

**Comment by ingoldsby** [comment]
Do we want to go with pre-defined options like 30 seconds, 60 seconds, 2 minutes, 5 minutes, 10 minutes or allow them to enter their own period (in seconds)?

**Comment by w1tw0lf** [comment]
Set default to 60, but the option to change to what the user wants to set it to.

**Comment by ingoldsby** [comment]
This has been released in v1.0.1

#19
